### ISSUE TITLE
Не меняются статусы заказов

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#12]
Добрый день. Отправляем PATCH запрос на изменение статуса. ответ приходит вроде норм. А на сайте статус заказа не меняется.
Поскажите что не так делаем? может в запросе ошибка какая?
Номер заказа 2596t5.

**Comment by piton66** [comment]
Вопрос снимается. С reason.id проблема была.

**Comment by ptrofimov** [comment]
reason.id теперь обязательное поле для заполнения при отмене заказа.

**Comment by ptrofimov** [comment]
Если проблемы нет, можете закрыть issue.

**Comment by ptrofimov** [comment]
Список доступных для выбора причин отмены заказа можно узнать тут https://github.com/onlinerby/onliner-cart-api/blob/master/docs/resources/shop_cancel_reasons.md

**Comment by piton66** [comment]
То что нужно. Спасибо
