### ISSUE TITLE
Не могу получить доступ к методам

### ISSUE THREAD

**Issue by Plyazhnic** [onlinerby/onliner-cart-api#14]
При отправки запросов приходит ответ access: denied. Ключи доступа брал для onliner-cart-api. Для апи b2b такого не наблюдалось. Также, в документации написано, что токены доступа для b2b и cart апи разной длины, но у меня получались одинаковыми

**Comment by ptrofimov** [comment]
Токены b2b для корзины не подходят. Для корзины в админке нужно создавать свои ключи. Напишите, какой client ID отправляете. И номер магазина.

**Comment by Plyazhnic** [comment]
client id - ec721f8ffe17cf4dee0a
номер магазина - 14625

**Comment by ptrofimov** [comment]
Покажите кусок кода, который выполняет авторизацию и после нее запрос с токеном. Замените секрет и токен на звездочки.

**Comment by Plyazhnic** [comment]
![image](https://user-images.githubusercontent.com/32639566/44789996-be465000-aba6-11e8-8034-80386dfe1f83.png)
![image](https://user-images.githubusercontent.com/32639566/44790016-d1592000-aba6-11e8-88ba-96ff8cd2b10b.png)
1-е - получение токена, 2-е - получить заказы

**Comment by ptrofimov** [comment]
Замените https://b2bapi.onliner.by/oauth/token на http://requestbin.fullcontact.com/1f0qn3r1 и отправьте еще раз запрос на авторизацию.

**Comment by ptrofimov** [comment]
Вижу. Client ID и секрет нужно отправлять не в post body параметрах. У нас используется HTTP Basic авторизация. Секреты кодируются специальным образом и помещаются в заголовок Authorization. У RestClient наверняка должны быть методы для настройки HTTP Basic Authorization. Попробуйте посмотреть, что там доступно.

**Comment by Plyazhnic** [comment]
Все получилось. Спасибо
