### ISSUE TITLE
Передавать наш ID товара при заказе в корзине.

### ISSUE THREAD

**Issue by Denis-Leshchuk** [onlinerby/onliner-cart-api#15]
Добрый день! При заказе через корзину, вы передаете по апи много информации, но не хватает ед. необходимого для нас поля для связи вашей и нашей карточки, а именно нашего id товара.
![image](https://user-images.githubusercontent.com/43576738/46018316-3fc7ca00-c0e2-11e8-891b-c22056dd178d.png)

нужен
![image](https://user-images.githubusercontent.com/43576738/46018276-2cb4fa00-c0e2-11e8-8fcd-c85b497e3ef6.png)

**Comment by ptrofimov** [comment]
Опишите подробнее.

**Comment by Denis-Leshchuk** [comment]
> Опишите подробнее.

отредактировал

**Comment by ptrofimov** [comment]
ID товара, полученный от магазина, в данный момент не сохраняется при оформлении заказа и не может быть получен через API. Но мы передаем артикул товара. Вы можете использовать его для связки.

**Comment by Olden** [comment]
закрываю
