### ISSUE TITLE
Не могу получить заказы

### ISSUE THREAD

**Issue by amdby** [onlinerby/onliner-cart-api#17]
Здравствуйте. Помогите пожалуйста, такая вот проблема
делаю POST  запрос на b2bapi.onliner.by чтобы получить токен.
Получаю ответ: {"access_token":"a45487231c5555addec2ac978ee663e00f9a9bd8","expires_in":3600,"token_type":"bearer","scope":null}
После этого делаю GET  запрос на  cart.api.onliner.by
Адрес: /orders
client Id: мой id
client Secret: мой Secret
Authorization: Bearer a45487231c5555addec2ac978ee663e00f9a9bd8
Accept:  application/json; charset=utf-8
Получаю ответ: {"message":"Access denied"}
Что я делаю не так?

**Comment by sidorovich** [comment]
Приведенный в примере токен не похож на токен для доступа к корзине. Проверьте, что используете корректные clientId и clientSecret при авторизации. Для b2b и корзины они разные.

**Comment by tronicsby** [comment]
Этот токен был получен с логином и паролем для заливки прайсов.
Если заменить на логин и пароль для корзины, то токен = NULL

**Comment by tronicsby** [comment]
по этому и ответ Access denied

**Comment by amdby** [comment]
Сгенерировали новые clientID и clientSecret. с ними получаю вот такой ответ
{"access_token":"eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6MTY4OSwibmFtZSI6IkFNRC5ieSJ9LCJhcGlfdHlwZSI6ImNhcnQiLCJiMmJfb3BlcmF0b3IiOiIxNjg5QGFwaS1jbGllbnQuY2FydCIsImlhdCI6MTU0MzMyMjU1Nywic2NvcGVzIjpbXSwiZXhwIjoxNTQzMzI2MTU3fQ.7uW0qtp4dwNaLxKa-8YjO5W1Mo1BAOk2iDdjsH9dtKbsXusDdNDrpZSeeYsH4MJ93DJ647nsOaKH4pi_CCsZ5w","expires_in":3600,"token_type":"bearer","scope":null} но дальше все равно access denied.

**Comment by tronicsby** [comment]
в админке остались старые логин и пароль для AM_card
может мы не от туда берем данные?

**Comment by sidorovich** [comment]
а можно как-то с одного аккаунта общаться? а то я потерял суть проблемы.. У amdby токен выглядит корректно, если access denied, то проблема скорее всего в передаче авторизационных заголовков. 

про проблему tronicsby вообще ничего не понимаю. извините.

**Comment by tronicsby** [comment]
Это один и тот же вопрос. Просто я добавил информации, почему не такой токен у amdby. И попробовал сделать на php вместо 1с. (Amdby делает в 1С-Предприятие). Тот же результат.



Отправлено из мобильной Почты Mail.Ru


вторник, 27 ноября 2018 г., 17:33 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by sidorovich** [comment]
токен выглядит корректно, если access denied, то проблема скорее всего в передаче авторизационных заголовков.

можно попробовать использовать сторонний прокси для логирования запросов, но их нужно разделять между вами, чтобы понимать у кого конкретно и  в чем именно проблема.

amdby - шлите ваш запрос на адрес https://requestbin.fullcontact.com/1cvkr9c1 вместо https://cart.api.onliner.by/orders
tronicsby - для вас адрес http://requestbin.fullcontact.com/1h0t0le1

**Comment by amdby** [comment]
Повторю суть.
Пытаюсь получить заказы 
Использую для этого средства 1С. Токен получаю корректный.
Дальше делаю запрос к cart.api.onliner.by и получаю access denied.
Заголовки в запросе
Authorization: Bearer <Токен>
Accept: application/json; charset=utf-8
В качестве токена передаю значение "access_token".

**Comment by sidorovich** [comment]
@amdby отлично! все так! только давайте теперь запрос на https://requestbin.fullcontact.com/1cvkr9c1 вместо cart.api и посмотрим, что же именно приходит к нам на сервер. на всякий случай замечание: токен имеет срок жизни и может устаревать.

**Comment by amdby** [comment]
У меня ответ "ок"

**Comment by sidorovich** [comment]
токен невалидный. обрезан до 200 символов.

**Comment by amdby** [comment]
Отправил на последний адрес получил ответ "ok"

**Comment by sidorovich** [comment]
все равно пришел токен обрезанный:
"eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6MTY4OSwibmFtZSI6IkFNRC5ieSJ9LCJhcGlfdHlwZSI6ImNhcnQiLCJiMmJfb3BlcmF0b3IiOiIxNjg5QGFwaS1jbGllbnQuY2FydCIsIml"

requestbin не проксирует запросы на наш сервер, он всегда отвечает 200 ОК и сохраняет полное содержимое запроса, для удобства отладки. проверьте тип данных у переменной в которой сохраняете токен.

**Comment by tronicsby** [comment]
Все верно. У amdby обрезался токен до 200 знаков из-за установленного ограничения.

**Comment by Olden** [comment]
закрываю
