### ISSUE TITLE
Увеличение количества выгружаемых заказов.

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#18]
Добрый день.  Можно ли как-то увеличить количество выгружаемых заказов по API? 
Сейчас выгружается 50. Но этого мало.  
Например человек отменил заказ на сайте на след день , и к нам в систему эти данные не попадут если после этого заказа было 50 заказов. 
Было бы замечательно делать выбор в настройках сколько заказов выгружать.

**Comment by Olden** [comment]
Добрый день. Пожалуйста внимательно читайте документацию: есть параметр:


limit | integer | Лимит записей на странице, по умолчанию - 50, максимально - 100

а так же page, вы можете пагинировать выборку

**Comment by piton66** [comment]
Спасибо. Вижу.
