### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [onlinerby/onliner-cart-api#19]
Подскажите в чём 
получаю токен из примера - [https://yadi.sk/i/M8cjnBNOxMR98A](url)

`$token = getAccessToken::index(); //95da3fcf4a64a548999b0874b5d87f7408e4dc71
 $client = new Client();

        $headers = [
            'Authorization' => 'Bearer ' . $token,
            'Accept' => 'application/json; charset=utf-8',
        ];

        try {
            $response = $client->get('https://cart.api.onliner.by/orders', [
                'headers' => $headers
            ]);
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
        }`

**Comment by sidorovich** [comment]
Скорее всего некорректные client_id и client_secret, они отличаются для доступа к B2B API и Cart API. Корректный токен для доступа к Cart API несколько длиннее.

**Comment by dmitryvasilevskiy** [comment]
хм... да всё ок.... странно конечно... ибо пробовал пересоздавал client_secret... 
Спасибо
