### ISSUE TITLE
Обновление прайса через PUT запрос

### ISSUE THREAD

**Issue by samikadze** [onlinerby/onliner-cart-api#21]
Подскажите, пожалуйста, каким образом необходимо передавать csv файл с товарами методом PUT. Не нашел по этому вопросу ответа в документации.

И правильно ли я понимаю, что можно передавать тот же файл, который сейчас формируется для автоматического забора по ссылке?

**Comment by sidorovich** [comment]
1. https://github.com/onlinerby/onliner-b2b-api/blob/master/docs/price-lists/import/replace.md
В теле запроса передавайте содержимое CSV-файла. В заголовке Content-Type передавайте text/csv.

2. Да, все верно.
