### ISSUE TITLE
Магазин 1378 - запрос логов АПИ корзины за 15, 16 января

### ISSUE THREAD

**Issue by AlexanderSekerin** [onlinerby/onliner-cart-api#24]
Просьба предоставить информацию работы (протоколирование
операций) АПИ корзины за 15.01.2020 и 16.01.2020,  аккаунт №1378 «SOCKET.BY» Интересует, по какой причине осуществляются ошибки в процессе смены статусов, при условии что смена статусов осуществляется в соответствии с регламентов документации Onliner Cart API. 
(https://github.com/onlinerby/onliner-cart-api)

Например, такое произошло с заказами:

29A41T
826151

**Comment by sidorovich** [comment]
Хотелось бы больше технических деталей: какой именно запрос вы отправляете и какой ошибкой мы отвечаем?

Указанные заказы были оформлены со старой версии мобильного приложения каталога, они отмечены флагом new_flow=0 и они должны быть обработаны по старому жизненному циклу в соответствии с регламентов документации Onliner Cart API.
(https://github.com/onlinerby/onliner-cart-api)

**Comment by AlexanderSekerin** [comment]
1) Правильно понимаем, что когда мобильные приложения у людей постепенно обновятся, то таких ситуаций больше не будет?

2) А вы могли бы со своей стороны поставить заглушку на отправку заказов со старых версий приложения? 
Поясним, ваш техпом ввёл нас в заблуждение. Они сообщали, что начинает работать новая версия статусов и никаких альтернатив нет. 
Сейчас оказывается, что система имеет 2 ветвления по обработке корзин...

**Comment by sidorovich** [comment]
1. Да, доля новых приложений постепенно увеличивается. В течении месяца может быть двух должно обновиться большинство устройств и мы прекратим полностью серверную поддержку старых версий мобильных приложений.

2. Можем ее поставить только для Вашего магазина, но это чревато тем, что Вы будете получать меньше заказов :) Лично мы не готовы на это. К сожалению бесшовный переход неизбежное зло как для наших покупателей, так и для магазинов, потому что очень малое количество наших клиентов могут одномоментно синхронно минута в минуту выполнять обновление как своих систем, так и наших мобильных приложений.

Скорее всего вы неправильно понял техподдержку. После окончательного перехода альтернатив не будет, но вынужденный переходный период есть. Вся техническая информация была опубликована заранее в этом репозитории. Не стесняйтесь следить за пулл-реквестами, задавать уточняющие вопросы. Мы заинтересованы в том, чтобы наша документация была актуальна и понятна, но без обратной связи этого сложно добиться.

Извините за задержку с ответом, уведомление о Вашем ответе было очень поздно и прошло случайно мимо всех технических специалистов.

**Comment by AlexanderSekerin** [comment]
Теперь ситуация ясна. Благодарим за ответ.
