### ISSUE TITLE
База адресов

### ISSUE THREAD

**Issue by dmitriyp228** [onlinerby/onliner-cart-api#26]
Вечер добрый, подскажите плс, вы используете базу адресов СОАТО?

**Comment by sidorovich** [comment]
Похоже на то, здесь брали http://ate.nca.by/
Но во-первых она может быть недостаточно актуальна, а во-вторых, в нее вроде бы вносились какие-то правки на уровне мелких населенных пунктов и далее.

А вы, простите, с какой целью интересуетесь? :) Просто мы не заявляли публичную поддержку какой-либо адресной информации. Поэтому эти вещи не документированы и мы вносим изменения без оглядки.

**Comment by dmitriyp228** [comment]
Да, это то что нам нужно. При подтверждении заказа нам важно идентифицировать адрес, дабы он был геокодированым )

**Comment by sidorovich** [comment]
Населенный пункт будет соответствовать. Улица, дом и т.д. могут не соответствовать, так как мы сделали подсказки для пользователя, но оставили эти поля со свободным вводом, чтобы не  сильно зависеть от актуальности базы данных.
