### ISSUE TITLE
Емай покупателя.

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#27]
Добрый день. Емайл покупателя стал передаваться в виде m2366k@orders.onliner.by.  А не его емайл при регистрации.  Емайл покупателя не передается больше?

**Comment by Olden** [comment]
В рамках новой корзины и безопасности покупателя мы передаём e-mail покупателя в проксированном виде. 
Вся переписка в рамках заказа передаётся как покупателю, так и продавцу.

**Comment by piton66** [comment]
т.е по апи получить реальный емайл покупателя нельзя?

**Comment by Olden** [comment]
Нет

**Comment by piton66** [comment]
Или на это емайл можно писать и покупатель получит письмо?

**Comment by Olden** [comment]
В рамках действующего заказа можно писать и покупатель получит письмо, сможет на него ответить при необходимости и магазин его ответ тоже получит

**Comment by piton66** [comment]
понял. спасибо.
