### ISSUE TITLE
Не могу получить данные о заказе по его номеру

### ISSUE THREAD

**Issue by tronicsby** [onlinerby/onliner-cart-api#3]
Добрый день
Не могу получить данные о заказе по его номеру.

**Comment by BNSby** [comment]
Присоединяюсь вопросу.
Запросы вида: https://cart.api.onliner.by/orders/498e6 всегда возвращают ответ вида
`{
    "message": "Заказ 498e6 не найден"
}`

**Comment by sidorovich** [comment]
Укажите, пожалуйста, полный запрос с заголовками. Такое возможно, если указан неправильный или просроченный авторизационный токен.

**Comment by tronicsby** [comment]
вот пример работы скрипта





-- 
tronics.by

**Comment by sidorovich** [comment]
@tronicsby ничего не вижу, пустой комментарий

**Comment by tronicsby** [comment]
function api_orders($url,$token,$method,$headers) {
	$process = curl_init($url);
	curl_setopt($process, CURLOPT_HTTPHEADER,$headers);
	curl_setopt($process, CURLOPT_CUSTOMREQUEST, $method);
	curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
	curl_setopt($process, CURLOPT_POSTFIELDS, $data);
	$result = curl_exec($process);
	curl_close($process);
	return $result;
}

$result=api_orders('https://cart.api.onliner.by/orders/'.$orderKey.'/',$token,'GET',array('Accept: application/json','charset=utf-8','Authorization: Bearer '.$token));

**Comment by sidorovich** [comment]
```php
var_dump($token);
```

**Comment by tronicsby** [comment]
string(303) "eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6IjE2ODkifSwiYjJiX29wZXJhdG9yIjoiMTY4OUBhcGktY2xpZW50LmNhcnQiLCJpYXQiOjE0NzUxNDMyODQsInNjb3BlcyI6W10sImV4cCI6MTQ3NTE0Njg4NH0.TR3vQ2cDKf6PsZBJpbQ_xQ88tuqWRRisiQJmFYDm0CTJs6pfFpC5YRFRhxhmkfiHWEgq3XZB33gSJ0SXQYa5hw"

**Comment by sidorovich** [comment]
токен выдан для магазина #1689 а вот указанный заказ связан с чужим магазином.

**Comment by tronicsby** [comment]
я же не указывал нигде номер заказа

**Comment by sidorovich** [comment]
токен вы получали при авторизации по секретным данным магазина

**Comment by tronicsby** [comment]
все правильно 
1689 - это наш магазин.
вот для примера номера заказов:
ae983
221t4
6t149

**Comment by tronicsby** [comment]
на данный момент ответ:
301 Moved Permanently

**Comment by tronicsby** [comment]
раньше был в виде json
как в сообщении от BNSby (см.выше)

**Comment by sidorovich** [comment]
уберите слеш в конце URL, либо включите переход по редиректам для CURL `curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);`

**Comment by tronicsby** [comment]
string(303) "eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6IjE2ODkifSwiYjJiX29wZXJhdG9yIjoiMTY4OUBhcGktY2xpZW50LmNhcnQiLCJpYXQiOjE0NzUxNDQ2MjksInNjb3BlcyI6W10sImV4cCI6MTQ3NTE0ODIyOX0.IV-f4c9PnHPIGSzMKhApa3u3q3uHpDoXUewdbQ9uHIyTVQvRp5aJq4i_SlKUG4v_A-Z2-fHMBKYyf8YLG6H--g"
{"message":"Заказ ae983 не найден"}
{"message":"Заказ 221t4 не найден"}
{"message":"Заказ 7t39e не найден"}
{"message":"Заказ 6t149 не найден"}
{"message":"Заказ k1k29 не найден"}
{"message":"Заказ k17a7 не найден"}
{"message":"Заказ e6448 не найден"}
{"message":"Заказ 85kt2 не найден"}
{"message":"Заказ 6e554 не найден"}
{"message":"Заказ 488m6 не найден"}
{"message":"Заказ 71815 не найден"}
{"message":"Заказ k2a76 не найден"}
{"message":"Заказ et5m4 не найден"}
{"message":"Заказ 92467 не найден"}
{"message":"Заказ 6k8e4 не найден"}
{"message":"Заказ 8t12e не найден"}
{"message":"Заказ 24t14 не найден"}
{"message":"Заказ t29k1 не найден"}
{"message":"Заказ 81114 не найден"}
{"message":"Заказ 72ek1 не найден"}
{"message":"Заказ mmk11 не найден"}
{"message":"Заказ 8e426 не найден"}
{"message":"Заказ k2m53 не найден"}

**Comment by sidorovich** [comment]
воспроизвел, будем разбираться. до конца дня постараемся ответить.

**Comment by sidorovich** [comment]
@tronicsby была проблема на нашей стороне с проверкой токена. можете перезапросить токен и попробовать снова. если все хорошо - закрывайте задачу.
