### ISSUE TITLE
Перестала работать изменение статуса заказа с new на processing

### ISSUE THREAD

**Issue by MrMurom** [onlinerby/onliner-cart-api#33]
Перестала работать изменение статуса заказа с new на processing.
Изменение статуса идет через 1с. Отправляю запрос 
patch с авторизацией и "{""status"": ""processing""}"
В ответ получаю 403 ошибку без комментариев.

**Comment by Olden** [comment]
Добрый день. Пришлите пожалуйста то что вы шлете в заголовку Authorization на почту ask@onliner.by

**Comment by Olden** [comment]
И скажите ошибка сейчас есть? или она была ночью?

**Comment by MrMurom** [comment]
Сейчас тоже есть.
Ошибка отправки файла на сервер. Код ошибки: 403
{"message":"Access denied"}

**Comment by Olden** [comment]
bearer пишется с большой буквы

**Comment by MrMurom** [comment]
В документации с маленькой написано
PATCH /orders/qz2wa
Authorization: bearer <token>
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8

**Comment by Olden** [comment]
Именно на этой странице только что исправил да, но на главной https://github.com/onlinerby/onliner-cart-api#onliner-cart-api было указано корректно.

**Comment by MrMurom** [comment]
Помогло. Проблема решилась.
