### ISSUE TITLE
Полученіе данных із заказа

### ISSUE THREAD

**Issue by AMDby1689** [onlinerby/onliner-cart-api#34]
Можно лі получать данные по апі із заказа  с кодом статуса "processing", адрес номер телефона і т.д

**Comment by sidorovich** [comment]
Контактная информация пользователя и адрес доставки для магазина будут доступны, когда заказ находится в статусах:

В обработке
Подтвержден
Передан в доставку
Доставлен

**Comment by AMDby1689** [comment]
Т.е уже сейчас мы сможем скачівать?

**Comment by sidorovich** [comment]
да, все должно работать. если не работает, присылайте номер заказа, пример запроса, дату и время запроса.

**Comment by AMDby1689** [comment]
Номер заказа: 9TA9K7
когда ставлю processing
ошибка
Недопустимый переход статусов

**Comment by sidorovich** [comment]
В данном случае нужен пример запроса от вас.
Судя по базе в данный момент заказ уже находится в статусе processing.

**Comment by AMDby1689** [comment]
Разобрались
