### ISSUE TITLE
Причина отмены заказа (Иное)

### ISSUE THREAD

**Issue by ahalay994** [onlinerby/onliner-cart-api#36]
Добрый день. Пытаюсь установить кастомный комментарий для отмены заказа (id = 7). В поле `comment` указываю причину, но эта причина не указывается в личном кабинете пользователя, а отображается просто как `Иное`. Как можно отменить заказ, указав свою личную причину в комментарии, чтобы она отображалась у пользователя в личном кабинете?

**Comment by sidorovich** [comment]
в случае отмены заказа магазином, комментарий пользователю не отображается
это бизнес-требование, с чем это связано, к сожалению, сегодня я вам не подскажу.
