### ISSUE TITLE
Поля адреса

### ISSUE THREAD

**Issue by ahalay994** [onlinerby/onliner-cart-api#39]
Здравствуйте. Можете пожалуйста сделать так, чтобы при заказе, в поле Улица можно было ввести только улицу, так как некоторые люди вписывают туда весь адрес, что данные по API приходят не верные.

**Comment by sidorovich** [comment]
Добрый день! 
Нет, не можем.

Для нас улица это строковое поле со свободным вводом, для которого есть подсказка. Мы максимально прикладываем усилия, чтобы пользователь выбрал улицу из списка, однако мы не ограничиваем пользователя только выбором из него, так как не обладаем актуальным списком улиц для всей нашей страны и не можем отказать пользователю в оформлении заказа только лишь на этом основании. 

Очень рад, что Вы уверены в своей адресной базе и готовы отказываться от клиентов, если они не могут найти свою улицу в новом микрорайоне!

В свою очередь мы открыты к идеям, как проводить такую проверку максимально корректно и поддерживать ее актуальной оперативно и бесплатно при этом не делясь персональной информацией наших клиентов со сторонними сервисами. Спасибо!
