### ISSUE TITLE
Стоимость доставки

### ISSUE THREAD

**Issue by ahalay994** [onlinerby/onliner-cart-api#43]
Добрый день. не подскажете пожалуйста, можно ли разграничить стоимость доставки продукции по категориям (ресторанам). У нас рестораны являются категориями и у каждого ресторана свой минимальный порог стоимости доставки в зависимости от суммы заказа. К примеру: человек делает заказ с одного ресторана на такую сумму, что доставка составляет 2 рубля, а с другого ресторана на сумму, что доставка составляет 4 рубля, и надо, чтобы итого сумма за доставку была не 4 рубля, а 6 рублей (так это доставка с разных ресторанов). Можно ли как-нибудь сделать данное разграничение?

**Comment by sidorovich** [comment]
Боюсь что это не технический вопрос. Обратитесь, пожалуйста, в отдел поддержки клиентов. Актуальные контакты Вы можете найти в личном кабинете по адресу https://b2b.onliner.by/
