### ISSUE TITLE
Не импортируется информация по самовывозам через АПИ

### ISSUE THREAD

**Issue by AMDby1689** [onlinerby/onliner-cart-api#46]
![image](https://user-images.githubusercontent.com/62288299/86127193-2f7b2500-bae8-11ea-94c1-2f80c2722d26.png)
а вот так в админке
![image](https://user-images.githubusercontent.com/62288299/86127262-4588e580-bae8-11ea-88ba-1a4f8b60709f.png)
Что нужно изменить чтобы к нам выгружался адрес пвз

**Comment by sidorovich** [comment]
У вас на первом скриншоте заказ в статусе Новый, а на втором в статусе Подтвержден.
Так как мы храним эту информацию в тех же самых полях, то на эту информацию распространяются правила скрытия контактов покупателя.

Контактная информация пользователя и адрес доставки для магазина будут доступны, когда заказ находится в статусах:

В обработке
Подтвержден
Передан в доставку
Доставлен

см. https://github.com/onlinerby/onliner-cart-api#%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D1%8B-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0-%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D1%86%D0%B8%D0%BA%D0%BB-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0

**Comment by AMDby1689** [comment]
![image](https://user-images.githubusercontent.com/62288299/86131153-f3e35980-baed-11ea-9e99-bcf8d70c3caa.png)
вот заказ со статусом подтвержден и ничего нет

**Comment by sidorovich** [comment]
А вы из каких полей ответа берете информаци?
Вам должна была приходить рассылка на изменения в документации.

Ознакомьтесь, пожалуйста, с изменениями от 05.06.2020 и свежее.
https://github.com/onlinerby/onliner-cart-api/blob/master/CHANGELOG.md#05062020

**Comment by AMDby1689** [comment]
Если заказ не самовывоз, то адрес у нас есть
![image](https://user-images.githubusercontent.com/62288299/86131991-feeab980-baee-11ea-8145-3e52d733d73c.png)

Адреса нет только когда заказ на самовывоз

**Comment by sidorovich** [comment]
<img width="1142" alt="Снимок экрана 2020-06-30 в 16 43 38" src="https://user-images.githubusercontent.com/3040359/86133358-dd8acd00-baf0-11ea-82c5-21c3d4c33fc7.png">

**Comment by sidorovich** [comment]
Почитайте, пожалуйста, документацию. Мы старались, чтобы ее описать. Там появились новые фичи :)
