### ISSUE TITLE
Вопрос по user_id

### ISSUE THREAD

**Issue by Revialas** [onlinerby/onliner-cart-api#47]
Здравствуйте. 
Скажите пожалуйста, а переменная user_id (к примеру в методе GET /orders/{orderKey}) постоянна у конкретного покупателя? Можно ли на неё опираться в системе когда поступил новый заказ и привязать его к клиенту с таким же user_id в локальной базе?

**Comment by sidorovich** [comment]
можно, постоянный уникальный идентификатор пользователя в нашей базе
