### ISSUE TITLE
Вопрос по id пвз

### ISSUE THREAD

**Issue by Revialas** [onlinerby/onliner-cart-api#48]
Здравствуйте.
Методом GET /orders/{orderKey} при получение данных заказа с пвз есть переменная [delivery][pickup_point][id]. Я так понимаю это внутренний id созданного нами в онлайнере пвз. Скажите, как получить id всех пвз которые мы создали?

**Comment by sidorovich** [comment]
Мы не планировали реализовывать механизм для получения такой информации. Могу вручную сделать для вас выгрузку, если подскажете Ваш номер магазина
