### ISSUE TITLE
405 ошибка при попытке подтвердить статус доставки в ПВЗ

### ISSUE THREAD

**Issue by MrMurom** [onlinerby/onliner-cart-api#49]
Добрый день.
При попытке подтвердить статус доставки заказа в ПВЗ получаю ошибку 405
Заказ находится в статусе "Передан в доставку"
Способ доставки указан "В пункт выдачи"

**запрос**
 /orders/e71336/pickup-point-delivered
**заголовки**
`"Content-Type"	"application/json; charset=utf-8"
"Accept"	"application/json; charset=utf-8"
"Authorization"	"Bearer  xxxx"` 
**тело запроса**
`{
"comment": "Ваш заказ номер ONLe71336 прибыл в ПВЗ"
}`

В чем может быть ошибка?

**Comment by kamadoss** [comment]
Добрый день! 
405 ошибка означает неправильно указанный http-метод. Данный роут обрабатывает только POST-запросы, убедитесь что вы по ошибке не указали другой метод. Если ошибка повторится - пришлите нам полное тело http запроса.

**Comment by MrMurom** [comment]
Оправляю именно POST запрос.
Прислать полное тела запроса нет возможности. 
Запрос программно отправляется через 1с.

**Comment by kamadoss** [comment]
Очевидно, ваше приложение, всё же, отправляет PUT запрос. 
Для дебага запроса к нашему приложению могу вам порекомендовать воспользоваться сторонним сервисом вроде https://requestbin.com/, где можно отслеживать полную информацию по отправляемым запросам - просто вместо эндпоинта нашего приложения в коде вашего приложения указываете выданный сервисом урл.

**Comment by MrMurom** [comment]
Проверил запросы через сервис https://requestbin.com/
Видно по логам что я отправляю POST запрос.
Подскажите в чем еще проблема ?
Скрин ниже

![изображение](https://user-images.githubusercontent.com/60186745/86916116-c28d0e00-c12b-11ea-8f6d-2fa90fd93313.png)

**Comment by kamadoss** [comment]
Можете прислать полный url, по которому вы к нам делаете запросы?

**Comment by MrMurom** [comment]
Запросы посылаю через соединение с сервером 
сервер cart.api.onliner.by
порт 443
урл /orders/k7t83e/pickup-point-delivered

полный урл будет таким
 
https://cart.api.onliner.by/orders/k7t83e/pickup-point-delivered

**Comment by sidorovich** [comment]
на какой операционной системе работает ваш код?

**Comment by sidorovich** [comment]
и номер вашего магазина подскажите

**Comment by sidorovich** [comment]
у нас запрос проходит по указанным данным. попробуем сторонним клиентом на вашей стороне исполнить данный запрос. сию мы получаем в ответ 409, и сообщение "Отметка о поступлении заказа в пункт выдачи уже есть", что говорит о том, что проблем у нас на HTTP слое нет и ошибка 405 возникала обоснованно.
<img width="1333" alt="Снимок экрана 2020-07-10 в 12 56 17" src="https://user-images.githubusercontent.com/3040359/87142334-1410d680-c2ad-11ea-88fe-7d43f2f06ce1.png">

**Comment by MrMurom** [comment]
> 
> 
> на какой операционной системе работает ваш код?

Windows server

> 
> 
> и номер вашего магазина подскажите

2033 



> у нас запрос проходит по указанным данным. попробуем сторонним клиентом на вашей стороне исполнить данный запрос. сию мы получаем в ответ 409, и сообщение "Отметка о поступлении заказа в пункт выдачи уже есть", что говорит о том, что проблем у нас на HTTP слое нет и ошибка 405 возникала обоснованно.

Я не понимаю все равно почему мне приходит 405 ошибка. Что не так в нашем запросе ? Готов связаться с вами, вместе посмотреть, предоставить доступы, но надо как-то решить проблему.

**Comment by sidorovich** [comment]
а какая версия Windows server? попробуем найти для вас клиент для выполнения запроса

**Comment by MrMurom** [comment]
> 
> 
> а какая версия Windows server? попробуем найти для вас клиент для выполнения запроса

Windows server 2008 R2 Enterprise Build 7601 x64

**Comment by sidorovich** [comment]
попробуйте установить клиент curl https://curl.haxx.se/windows/

и в консоли выполнить запрос, предварительно заменив  %TOKEN% на ваш свежий авторизационный токен

```
curl --request POST \
  --url https://cart.api.onliner.by/orders/k7t83e/pickup-point-delivered \
  --header 'accept: application/json; charset=utf-8' \
  --header 'authorization: Bearer %TOKEN%' \
  --header 'content-type: application/json; charset=utf-8' \
  --cookie ouid=snyBDF77QUARfV6hJrBGAg%3D%3D \
  --data '{"comment": "Ваш заказ номер ONLe71336 прибыл в ПВЗ"}'
```

**Comment by sidorovich** [comment]
если получите невнятный ответ, то скиньте сюда полный вывод консоли или скриншот с ним

**Comment by MrMurom** [comment]
![изображение](https://user-images.githubusercontent.com/60186745/87156627-a45b1580-c2c5-11ea-89f7-cad64808d2ac.png)
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\murom\curl-7.71.1-win64-mingw\bin>curl.exe --request POST --url https:/
/cart.api.onliner.by/orders/k7t83e/pickup-point-delivered --header 'accept: appl
ication/json; charset=utf-8' --header 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJ
hbGciOiJIUzUxMiJ9.eyJ1c2VyX3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6MjAzMy
wibmFtZSI6IjI0c2hvcC5ieSJ9LCJhcGlfdHlwZSI6ImNhcnQiLCJiMmJfb3BlcmF0b3IiOiIyMDMzQG
FwaS1jbGllbnQuY2FydCIsImlhdCI6MTU5NDM4NDgzMiwic2NvcGVzIjpbXSwiZXhwIjoxNTk0Mzg4ND
MyfQ.XFQnd71Pf5Jd_veLyD76WTIHNFhD9U-59qJvBFJaEHCdLO6S_4sD9pprXzptLkdDeBoQEbfvIgQ
1jgxPKNDa8A' --header 'content-type: application/json; charset=utf-8'--data '{"c
omment": "123123123"}'
{"message":"Content-Type supports only application\/json"}curl: (6) Could not re
solve host: application
curl: (6) Could not resolve host: charset=utf-8'
curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyX
3R5cGUiOiJiMmJfc2hvcCIsInVzZXJfZGF0YSI6eyJpZCI6MjAzMywibmFtZSI6IjI0c2hvcC5ieSJ9L
CJhcGlfdHlwZSI6ImNhcnQiLCJiMmJfb3BlcmF0b3IiOiIyMDMzQGFwaS1jbGllbnQuY2FydCIsImlhd
CI6MTU5NDM4NDgzMiwic2NvcG
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: charset=utf-8'--data
curl: (3) unmatched brace in URL position 2:
'{comment:
 ^

**Comment by sidorovich** [comment]
из-за разности операционных систем, надо кавычки заменить

```
curl --request POST --url https://cart.api.onliner.by/orders/k7t83e/pickup-point-delivered --header "accept: application/json; charset=utf-8" --header "authorization: Bearer %TOKEN%" --header "content-type: application/json; charset=utf-8" --data "{'comment': 'Ваш заказ номер ONLe71336 прибыл в ПВЗ'}"
```

Расшифровать полученный ответ, можно на сайте https://jsoneditoronline.org/ мы просто кириллицу отдаем как юникод символы

**Comment by MrMurom** [comment]
Удалось найти решение вопроса. Очевидно очередной баг платформы 1с.
Если через одно соединение  вызывать метод "patch" а после него метод "post", то получаю от вас ошибку 405.
Если создать новое соединение с аналогичными параметрами и вызвать метод "post" через него, то все работает.  
И понятно почему отрабатывал метод "post" через https://requestbin.com/ - я его запускал через отдельное соединение, чтоб не мучаться с авторизацией.
