### ISSUE TITLE
Цены и количество заказанных товаров

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-cart-api#50]
Добрый день. Есть ли возможность сделать, чтобы api отдавало количество конкретного товара в заказе, а также его цену? На данный момент указывается только общая стоимость заказа + стоимость доставки, а также общее количество заказанных позиций. Также было бы очень удобно, если бы было добавлено поле с id предложения. То есть, хотелось бы, чтобы была реализована возможность получения информации типа:

заказанный товар 1
- наименование: А
- количество: 2шт
- цены: 10 рублей
- id предложения: 123

заказанный товар 2 
- наименование: Б
- количество: 1шт
- цены: 20 рублей
- id предложения: 234

**Comment by julia-korotkina** [comment]
Благодарю за информацию. На данный момент мне этого вполне достаточно. Если когда-то появится поле id предложения, буду рада. Спасибо!

**Comment by sidorovich** [comment]
Добавили идентификатор ценового предложения в ответы API
https://github.com/onlinerby/onliner-cart-api/blob/master/CHANGELOG.md#17092020
