### ISSUE TITLE
ошиба в GET /orders?include=shop,positions

### ISSUE THREAD

**Issue by pravlutski** [onlinerby/onliner-cart-api#53]
не могу понять. пока статус заказа в new в ответе не появляется блок [contact]
..........
    [contact] => Array
        (
            [name] => test
            [first_name] => test
            [last_name] => test
            [middle_name] => 
            [email] => k45t45@orders.onliner.by
            [phone] => +375 29 119-29-52
        )
дело в том что я получаю заказы себе в админку на сайт и создаю заказы, пользователя. и вот пользователя я создать не могу. соответственно и заказ т.к. он привязан к пользователю.

этот блок в ответе то есть то его нет. после перевода в processing появляется. ну и вроде иногда в статусе new тоже есть (возможно через какое то время)
как мне правильно получать заказы?

**Comment by sidorovich** [comment]
Внимательно читайте документацию!

Контактная информация пользователя и адрес доставки для магазина будут доступны, когда заказ находится в статусах:

В обработке
Подтвержден
Передан в доставку
Доставлен

Это сделано для того, чтобы магазин подтверждал только заказы по реальному наличию товаров, а не пытался продать покупателю другой товар получив его контакты.
