### ISSUE TITLE
Получение информации о geo_town_id

### ISSUE THREAD

**Issue by alsudnik** [onlinerby/onliner-cart-api#55]
При обработке заказа  адрес выгружается без указания области и района. 
Пример: д. Копище есть как Минского района, так и Вилейского.
Есть значение [geo_town_id] => 19834, можно ли по нему получать полный адрес включая область и район?

**Comment by sidorovich** [comment]
19834 это Минское Копище, Боровлянский с/с
но в целом замечание дельное - будем решать этот вопрос и как-то передавать эту информацию

**Comment by sidorovich** [comment]
https://github.com/onlinerby/onliner-cart-api/blob/master/CHANGELOG.md#5112020
самый быстрый вариант.
оставим этот роут публичным для магазинов, возможно в дальнейшем что-то поменяем.
обратите внимание, что там другой домен!

**Comment by alsudnik** [comment]
Благодарю, все работает

**Comment by sidorovich** [comment]
закройте этот запрос, если все хорошо! спасибо
