### ISSUE TITLE
Сбой в получении и обработке заказов

### ISSUE THREAD

**Issue by julia-korotkina** [onlinerby/onliner-cart-api#57]
Добрый день. Последние несколько месяцев пользовались вашим api для заказов - получение, подтверждение и тд. Всё работало хорошо и без сбоев. А сегодня с утра два заказа отменились - один "отменен системой", хотя с клиентом связались, подтвердили, а второй упущен - через api его почему-то не получили. Вероятнее всего наши запросы до вас по какой-то причине не дошли. Сейчас новые заказы появляются, обрабатываются, хотя ни вчера, ни сегодня ничего нигде не меняли. Скажите, пожалуйста, можно проверить, доходили ли до вас наши запросы? Это было в период где-то с 9.00 до 10.00.

**Comment by Olden** [comment]
добрый день. с какого ip адреса вы слали нам запросы?

**Comment by julia-korotkina** [comment]
93.125.99.126

**Comment by Olden** [comment]
@julia-korotkina скажите ваш email, отправлю на него логи ваших запросов, сможете посмотреть

**Comment by julia-korotkina** [comment]
juliakorotkina@gmail.com

**Comment by julia-korotkina** [comment]
Спасибо!
