### ISSUE TITLE
Загрузка заказов. 100 последних.

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#61]
Загружается максимум 100 последних заказов. Это 100 последних созданных.  А если заказ был создан несколько дней назад и изменен,  он не попадает в 100 последних созданных, то данные о нем мы не получаем. Может отправлять 100 последних измененных заказов?

**Comment by sidorovich** [comment]
Внимательно читайте документацию!
https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/index.md

Вы можете запросить вторую страницу в списке, третью и так далее.
Так же Вы можете фильтровать заказы в выборке в зависимости от статуса заказа.

**Comment by piton66** [comment]
Так же Вы можете фильтровать заказы в выборке в зависимости от статуса заказа.  Спс . так и сделал.
