### ISSUE TITLE
Автоматическая выгрузка расходов

### ISSUE THREAD

**Issue by alex107412** [onlinerby/onliner-cart-api#63]
Необходимо реализовать автоматическую выгрузку данных из вкладки финансы, данные такие:
1. Категория товара - наименование товара - номер заказа - цена комиссии onliner byn с ндс
2. Каатегория товара - аукцион (название аукцион) - цена комиссии onliner byn с ндс
Наши магазины:
№3886
№2518
№19714
№19713

**Comment by sidorovich** [comment]
Это не вопрос техподдержки. Обращайтесь в отдел по работе с клиентами.
