### ISSUE TITLE
Дополнительные данные GET /orders

### ISSUE THREAD

**Issue by belshinaBY** [onlinerby/onliner-cart-api#64]
Просим доработать ответ запроса GET /orders на предмет добавления информации о количестве товара и его цене. На текущий момент присутствует информация об общем количестве и стоимости, что не совсем удобно при интеграции с другими учетными системами. Не совсем понятно какое количество товара было заказано клиентом если в заказе несколько позиций (вариант ответа до подтверждения магазином заявки).

**Comment by sidorovich** [comment]
https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/index.md#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%B8-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0-%D1%81-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%B5%D0%B9-%D0%BE-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D1%8F%D1%85-%D0%B8-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B5

Добавьте к URI запроса `?include=positions`
