### ISSUE TITLE
Возможность получить измененные заказы с указанной даты.

### ISSUE THREAD

**Issue by Serega456** [onlinerby/onliner-cart-api#65]
Возможность получить измененные заказы с указанной  даты (время). 
На данные момент можно получить только либо все заказы, либо по номеру, либо по какому статусу.

**Comment by sidorovich** [comment]
В данный момент сортировка заказов происходит убыванию даты создания заказа.
Вы может уменьшить или увеличить размер выборки на одной странице используя параметр limit
https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/index.md

В ближайшее время мы планируем пересмотреть механизм получения устаревших заказов (которые завершили свой жизненный цикл и уже либо доставлены, либо отменены и никак будут меняться).

Хотелось бы примеры, для чего вы планируете использовать данную выборку.

**Comment by Serega456** [comment]
Мне необходимо получить только измененные заказы с последнего момента выборки и зафиксировать их статус или например создать заказ в учетной системе если статус "Новый". Чтобы это сделать мне надо сначала получить все заказы, а потом по дате изменение их выбрать. Как то не рационально получается. И лимит тут не поможет, т.к. как я понял сортировка по дате создания.

**Comment by sidorovich** [comment]
Понял Вашу потребность. Дорабатывать выборку свежих заказов пока не планировали, но я помечу себе Ваше пожелание. К сожалению по срокам ничего подсказать не могу - ситуация сложная, трудно планировать работу на какой-то длительный период.

В текущих условиях могу посоветовать такие варианты:
- запоминать в системе номера новых заказов и потом по каждому заказу запрашивать актуальный статус (должно подойти, если у Вас не тысячи заказов в промежуточных статусах). для новых заказов делать запросы с фильтром по статусу "новый"
- запоминать самый старый заказ в не конечном статусе и самый новый заказ в ответе. в следующий раз выполнять постраничные запросы пока не найдете самый старый заказ, все заказы до самого нового заказа с прошлого запроса считать новыми. должно работать, так как сортировка по дате создания неизменна. явно нужно будет сделать гораздо меньше запросов, чем в предыдущем варианте.
