### ISSUE TITLE
Апи

### ISSUE THREAD

**Issue by derqas** [onlinerby/onliner-cart-api#7]
Было бы неплохо если бы добавили (в GET /orders) еще фильтры по полям status [new, confirmed, delivered ...], created_at (from - to) и updated_at (from - to)

**Comment by Olden** [comment]
Добрый день.

Фильтр по статусу есть: https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/index.md#Параметры-запроса

фильтрацию по датам передам на доработку.

**Comment by derqas** [comment]
да. что-то по "статусу" просмотрел )

**Comment by Olden** [comment]
@derqas если это все, закрывайте тикет;)

**Comment by derqas** [comment]
нет. остается  created_at (from - to) и updated_at (from - to)

**Comment by Olden** [comment]
ваш запрос я передал руководителю проекта, если они посчитают нужным это реализовывать, то об этом вы узнаете отсюда: https://github.com/onlinerby/onliner-cart-api/blob/master/CHANGELOG.md а пока предлагаю закрыть вопрос;)

**Comment by derqas** [comment]
ок )
