### ISSUE TITLE
Не меняет статус заказа на сайте.

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#73]
Добрый день. 
При попытке смены статуса выдает сообщение  message Validation failed errors status Недопустимый переход статусов. 
Номер заказа a1862e7. 
Передается статус delivered. Статус заказа на онлайнере - shipping. 
В чем может быть ошибка?

**Comment by KateTyush** [comment]
> a1862e7

Добрый день, а как вы меняете статус заказа? Заказ a1862e7 нужно завершать через приложение со сканирование QR кода

**Comment by piton66** [comment]
спасибо. разобрались.
