### ISSUE TITLE
Заявка Minipay в состоянии "Сделка".

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#78]
Добрый день. Статусы онлайн оплаты Заявка Minipay в состоянии "Сделка"  - это конечный статус по минипэй? 
Аналогичен статусу  Средства списаны ?

**Comment by akarashchuk** [comment]
Добрый день, да, "Сделка" - это конечный статус оплаты для Minipay

**Comment by piton66** [comment]
Спасибо.
