### ISSUE TITLE
Заказы в старой валюте

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#8]
День добрый.
Получил заказы из корзины. а они в старой валюте. Суммы в тысячах рублей.
И можно ли как-то настроить на получение не всех заказов а например за определенный период.

**Comment by sidorovich** [comment]
Добрый день! Покажите ваш запрос и тело ответа. По идее даже старые заказы, должны приходить с ценой и в деноминированной валюте.

**Comment by piton66** [comment]
В order_cost нормальная цена. В total_cost в старой валюте. 
Буду тогда order_cost использовать

**Comment by piton66** [comment]
А если в заказе 2 товара. Где мне увидеть стоимость каждого.

**Comment by sidorovich** [comment]
1. Все верно, используйте order_cost. Старое поле total_cost временно оставлено для совместимости со старыми клиентами. В будущем оно будет удалено.

2. 
https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/index.md
`GET GET /orders?include=positions`

Либо

https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/show.md
`GET /orders/{orderKey}?include=positions`

Внимательнее читайте документацию.

Если я ответил на Ваши вопросы - просьба закрыть данный стикер. Спасибо, что обратились!

**Comment by piton66** [comment]
Спасибо.

**Comment by piton66** [comment]
А сжатие gzip поддерживается?

**Comment by sidorovich** [comment]
Если верить заголовку ответа `Content-Encoding: gzip`, то должен поддерживать.
