### ISSUE TITLE
Изменение статуса заказа.

### ISSUE THREAD

**Issue by piton66** [onlinerby/onliner-cart-api#9]
Добрый день. Пытаюсь поменять статус заказа Методом patch. 
Получаю ответ сервера без ошибок. Но на сайте не меняется ничего.
Заказ новый. Хочу изменить статус на подтвержден.
status: confirmed

**Comment by ptrofimov** [comment]
Добрый день. Напишите номер заказа.

**Comment by piton66** [comment]
8a78e1

**Comment by ptrofimov** [comment]
Напишите дамп вашего запроса/ответа. (как в примере https://github.com/onlinerby/onliner-cart-api/blob/master/docs/order/update.md#Пример-запроса)

**Comment by piton66** [comment]
Неправильно тело запроса наверное формировалось. Сделал так. Заработало.
/orders/8a78e1?status=confirmed

**Comment by Olden** [comment]
👍

**Comment by sidorovich** [comment]
Передача параметров в query-параметрах запроса является недокументированным функционалом, который обеспечивает текущий фреймворк проекта. Мы не гарантируем, что данный запрос будет корректно выполняться в будущем. Настоятельно рекомендую передавать параметры в теле PATCH-запроса в JSON-формате с указанием заголовка Content-Type: application/json

**Comment by piton66** [comment]
День добрый. Когда заказ создан на сайте. Но не подтвержден менеджером.
При выгрузке не передаются данные покупателя.
Это так и есть. или я чего-то не заметил?

**Comment by sidorovich** [comment]
Все верно. Внимательнее читайте документацию:
https://github.com/onlinerby/onliner-cart-api

> Если заказ находится в статусах, отличных от "Подтвержден" или "Доставлен", то контактная информация пользователя и адрес доставки (кроме города) для магазина будут недоступны.

**Comment by piton66** [comment]
Все спасибо за помошь . Всё работает.

**Comment by piton66** [comment]
Передача параметров в query-параметрах запроса является недокументированным функционалом, который обеспечивает текущий фреймворк проекта. Мы не гарантируем, что данный запрос будет корректно выполняться в будущем. Настоятельно рекомендую передавать параметры в теле PATCH-запроса в JSON-формате с указанием заголовка Content-Type: application/json  )) Вот и настал этот момент))

**Comment by piton66** [comment]
Можно как-то передать закрытие заказа  в query-параметрах запроса.
